plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.r4remote.poweramp'
    compileSdk 36

    defaultConfig {
        applicationId 'dev.r4remote.poweramp'
        minSdk 26
        targetSdk 36
        versionCode 5
        versionName '0.5.0'

        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = false
    }

}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:deprecation']
}
